version: '3.8'

services:

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=social
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    volumes:
      - db-data:/var/lib/postgresql
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"

volumes:
  db-data:
